<?php
define('DEFAULT_RESULTS_LIMIT', 12);
define('INTELLIGENT_RESULTS_LIMIT', 6);
define('LISTING_NAME_STR_LENGTH', 24);
define('LISTING_DESCRIPTION_STR_LENGTH', 34);
define('TIME_MINUTE_INTERVAL', 30);
?>